name: Discord Bot

on:
  schedule:
    #- cron: '*/5 * * * *' # Run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Run bot
      run: node CrabBot.js
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
